/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JFrame;

/**
 *
 * @author Conta
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        this.setResizable(false);
        initComponents();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        JDP = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        agregarEstudiante = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        agregarProfesor = new javax.swing.JMenuItem();
        menuEstudiante1 = new javax.swing.JMenu();
        actividadesCombox = new javax.swing.JMenuItem();
        reportes = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JDPLayout = new javax.swing.GroupLayout(JDP);
        JDP.setLayout(JDPLayout);
        JDPLayout.setHorizontalGroup(
            JDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        JDPLayout.setVerticalGroup(
            JDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        menuInicio.setText("Inicio");

        menuSalir.setText("Salir");
        menuInicio.add(menuSalir);

        jMenuBar1.add(menuInicio);

        jMenu2.setText("Estudiantes");

        agregarEstudiante.setText("Agregar Estudiante");
        agregarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEstudianteActionPerformed(evt);
            }
        });
        jMenu2.add(agregarEstudiante);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Profesores");

        agregarProfesor.setText("Agregar Profesor");
        agregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProfesorActionPerformed(evt);
            }
        });
        jMenu3.add(agregarProfesor);

        jMenuBar1.add(jMenu3);

        menuEstudiante1.setText("Actividades");

        actividadesCombox.setText("Crear Cuaderno de Tiempo");
        actividadesCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actividadesComboxActionPerformed(evt);
            }
        });
        menuEstudiante1.add(actividadesCombox);

        reportes.setText("Ver Reportes");
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });
        menuEstudiante1.add(reportes);

        jMenuBar1.add(menuEstudiante1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDP, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDP, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actividadesComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actividadesComboxActionPerformed
        Cuaderno_De_Tiempo cuaderno = new Cuaderno_De_Tiempo();
        cuaderno.setVisible(true);
        JDP.add(cuaderno);
    }//GEN-LAST:event_actividadesComboxActionPerformed

    private void agregarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEstudianteActionPerformed
        Vista_Estudiante estudiante = new Vista_Estudiante();
        estudiante.setVisible(true);
        JDP.add(estudiante);
    }//GEN-LAST:event_agregarEstudianteActionPerformed

    private void agregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProfesorActionPerformed
        Vista_Profesor profesor = new Vista_Profesor();
        profesor.setVisible(true);
        JDP.add(profesor);
    }//GEN-LAST:event_agregarProfesorActionPerformed

    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
        Vista_Reporte reporte = new Vista_Reporte();
        reporte.setVisible(true);
        JDP.add(reporte);
    }//GEN-LAST:event_reportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDP;
    private javax.swing.JMenuItem actividadesCombox;
    private javax.swing.JMenuItem agregarEstudiante;
    private javax.swing.JMenuItem agregarProfesor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuEstudiante1;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem reportes;
    // End of variables declaration//GEN-END:variables
}
