/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Db;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Conta
 */
public class Vista_Reporte extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Reporte
     */
    public Vista_Reporte() {
        initComponents();
        mostrardatos("");
    }
    
    void mostrardatos(String valor){
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("Nombre");
    modelo.addColumn("Fecha");
    modelo.addColumn("Fecha Inicio");
    modelo.addColumn("Fecha Fin");
    modelo.addColumn("Tiempo Interrupción");
    modelo.addColumn("Comentario");
    modelo.addColumn("Completado");
    modelo.addColumn("Unidad");
    modelo.addColumn("Estudiante");
    modelo.addColumn("Profesor");
    modelo.addColumn("Materia");
    modelo.addColumn("Categoría");
    
    tbReportes.setModel(modelo);
    String sql="";
    if(valor.equals(""))
    {
        sql="SELECT * FROM actividades";
    }
    else{
        sql="SELECT * FROM actividades WHERE id='"+valor+"'";
    }
 
    String []datos = new String [13];
        try {
            Controlador.Db con = new Controlador.Db();
            Connection cn = con.conexion();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=rs.getString(10);
                datos[10]=rs.getString(11);
                datos[11]=rs.getString(12);
                datos[12]=rs.getString(13);
                modelo.addRow(datos);
            }
            tbReportes.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Cuaderno_De_Tiempo.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbReportes = new javax.swing.JTable();

        setTitle("Reporte de Actividades");

        tbReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Actividad", "Categoría", "Fecha Inicio", "Fecha Fin", "Tiempo Acumulado", "Tiempo Pausado"
            }
        ));
        jScrollPane1.setViewportView(tbReportes);
        if (tbReportes.getColumnModel().getColumnCount() > 0) {
            tbReportes.getColumnModel().getColumn(0).setHeaderValue("ID");
            tbReportes.getColumnModel().getColumn(1).setHeaderValue("Actividad");
            tbReportes.getColumnModel().getColumn(2).setHeaderValue("Categoría");
            tbReportes.getColumnModel().getColumn(3).setHeaderValue("Fecha Inicio");
            tbReportes.getColumnModel().getColumn(4).setHeaderValue("Fecha Fin");
            tbReportes.getColumnModel().getColumn(5).setPreferredWidth(120);
            tbReportes.getColumnModel().getColumn(5).setHeaderValue("Tiempo Acumulado");
            tbReportes.getColumnModel().getColumn(6).setPreferredWidth(120);
            tbReportes.getColumnModel().getColumn(6).setHeaderValue("Tiempo Pausado");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbReportes;
    // End of variables declaration//GEN-END:variables
}
